#!/bin/bash

# ================================
# KEEP RULES
# add filenames, extensions, or patterns
# ================================
KEEP=(
    "PKGBUILD"
    ".SRCINFO"
    'config.*'
    '*.desktop'
    # "*.cfg"
    # "*.cfg/**"
)

# ================================
# SCRIPT
# ================================

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"

should_keep() {
    local item="$1"
    local name="$(basename "$item")"

    for rule in "${KEEP[@]}"; do
        [[ "$name" == $rule ]] && return 0
        [[ "$item" == $rule ]] && return 0
        [[ "$item" == */$rule ]] && return 0
        [[ "$item" == */$rule/* ]] && return 0
    done

    return 1
}

echo "== N0ctOS Clean-All =="
echo "Root: $REPO_ROOT"
echo ""

for subdir in "$REPO_ROOT"/*/; do
    [ -d "$subdir" ] || continue

    # skip folders
    [[ "$(basename "$subdir")" == "__deployed__" ]] && continue
    [[ "$(basename "$subdir")" == "n0ctos-keyring" ]] && continue

    echo ">> Cleaning: $(basename "$subdir")"

    cd ${subdir}
    rm -r src
    rm -r pkg
    rm *.tar.*
    echo ""
done

echo "== Done =="
