#!/bin/env bash

# THIS REPO SETS UP THE DEV ENVIRONMMENT TO AUTOMATE
# THE PROCESS OF PKG BUILDING AND DEPLOYING TO REPO

# RUN THIS SCRIPT ONCE

doc_url=https://n0ctaneteam.github.io/N0ctOS

mkdir ~/Projects/N0ctOS
cd ~/Projects/N0ctOS

echo "############################################################"
echo "###   Do u want to clone full repo ? (or just latest ?)  ###"
echo "############################################################"
echo "1 (latest) ; 2 (full)    [default:1]"
read git_clone_type

case $git_clone_type in
	"1")
		git_clone_type="latest"
		;;
	"2")
		git_clone_type="full"
		;;
	*)
		echo "couldn't understand"
		exit
		;;
esac

echo -e "\n\n\ncloning the $git_clone_type git(s)"
# clone the latest git
git clone https://github.com/n0ctaneteam/N0ctOS-PKGBUILDs.git
git clone https://github.com/n0ctaneteam/N0ctOS-pkg-repo.git


clear
echo "########################################"
echo "!!!        Dev Env setup done        !!!"
echo "########################################"

echo -e "\n\n"
echo -e "Read the docs for more info"
echo $doc_url