#!/bin/env bash

# THIS REPO SETS UP THE DEV ENVIRONMMENT TO AUTOMATE
# THE PROCESS OF PKG BUILDING AND DEPLOYING TO REPO

# RUN THIS SCRIPT ONCE

doc_url=https://n0ctaneteam.github.io/N0ctOS

mkdir ~/Projects/N0ctOS
cd ~/Projects/N0ctOS

echo "############################################################"
echo "###   Do u want to clone full repo ? (or just latest ?)  ###"
echo "############################################################"
echo "1 (latest) ; 2 (full)    [default:1]"
read git_clone_type

case $git_clone_type in
	"1")
		git_clone_type="latest"
		;;
	"2")
		git_clone_type="full"
		;;
	*)
		echo "couldn't understand"
		exit
		;;
esac

echo -e "\n\n\ncloning the $git_clone_type git(s)"
# clone the latest git
git clone https://github.com/n0ctaneteam/N0ctOS-PKGBUILDs.git
git clone https://github.com/n0ctaneteam/N0ctOS-pkg-repo.git

clear
echo "##########################################"
echo "!!!           Git clone done           !!!"
echo "##########################################"

echo -e "\n\n\n"
echo "############################################################"
echo "###   Do u want to remove this file ? (cz ts is useless)  ###"
echo "############################################################"
echo "1 (yes) ; 2 (no)    [default:1]"
read what_to_do_with_this_file

case $what_to_do_with_this_file in
	"1")
	  rm ./init 
		;;
	"*")
	  exit
		;;
esac

clear
echo "########################################"
echo "!!!        Dev Env setup done        !!!"
echo "########################################"

echo -e "\n\n"
echo -e "Read the docs for more info"
echo $doc_url