#!/bin/env bash
# THIS REPO SETS UP THE DEV ENVIRONMMENT TO AUTOMATE
# THE PROCESS OF PKG BUILDING AND DEPLOYING TO REPO
# RUN THIS SCRIPT ONCE
doc_url=https://n0ctaneteam.github.io/N0ctOS

# Array of script names
SCRIPTS=(
    "auto-all"
    "auto-changed"
    "build-all"
    "build-changed"
    "push-to-repo"
    "clean-all"
)

mkdir ~/Projects/N0ctOS
cd ~/Projects/N0ctOS

echo "############################################################"
echo "###   Do u want to clone full repo ? (or just latest ?)  ###"
echo "############################################################"
echo "1 (latest) ; 2 (full)    [default:1]"
read git_clone_type

case $git_clone_type in
    "2")
        git_clone_type="full"
        echo -e "\n\n\ncloning the $git_clone_type git"
        git clone https://github.com/n0ctaneteam/N0ctOS-PKGs.git
        ;;
    *)
        git_clone_type="latest"
        echo -e "\n\n\ncloning the $git_clone_type git"
        git clone --depth=1 https://github.com/n0ctaneteam/N0ctOS-PKGs.git
        ;;
esac


cd ~/Projects/N0ctOS/N0ctOS-PKGs
git lfs install
git lfs track "*.pkg.tar.zst"

for FILE in "${SCRIPTS[@]}"; do
    chmod +x ~/Projects/N0ctOS/N0ctOS-PKGs/"$FILE"
    echo "chmod-ed $FILE"
done

./gpg-key-set

# install gh cli
echo -e "\n\n\n\n\n\   Setup GH-CLI"
sudo pacman -Sy github-cli --needed --noconfirm

# authenticate (one time, interactive)
gh auth login

# =========================
# Done
# =========================
echo
echo "########################################"
echo "!!!        Dev Env setup done        !!!"
echo "########################################"
echo -e "\n\n"
echo -e "Read the docs for more info"
echo $doc_url