#!/bin/env bash
# 
# 
# PUSH THE PKG REPO
# 
# 

cd ~/Projects/N0ctOS/N0ctOS-PKGs/__deployed__/x86_64

rm -f N0ctOS-pkg-repo.{db,files}*

repo-add N0ctOS-pkg-repo.db.tar.zst *.pkg.tar.zst
rm -f N0ctOS-pkg-repo.db
rm -f N0ctOS-pkg-repo.files

mv -f N0ctOS-pkg-repo.db.tar.zst N0ctOS-pkg-repo.db
mv -f N0ctOS-pkg-repo.files.tar.zst N0ctOS-pkg-repo.files


cd ~/Projects/N0ctOS/N0ctOS-PKG

GIT_USER="$(git config user.name)"
CURRENT_TIME="$(date '+%Y-%m-%d %H:%M:%S')"

git checkout -b $GIT_USER//$CURRENT_TIME
git add .
git commit -m "Update by $GIT_USER at $CURRENT_TIME"
git push origin update

notify-send \
    -a 'N0ctOS PKG pusher' \
    -t 10000 \
    'N0ctOS PKG pusher:' \
    "Changes Pushed !!! Now wait for Being Pulled"